name: Fetch and extract docs
description: Gets the latest release from a repo, gets the docs tarball from that release, and extracts it.
inputs:
  subdir:
    description: Directory for release docs to be extracted to.
    required: true
  repo:
    description: Repository to get the .tar.gz file from.
    required: true
  tarball_prefix:
    description: Prefix used in the name of the .tar.gz file before the -(release number).tar.gz part.
    required: true
  token:
    description: Github token to use for CLI and actions.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get version of latest release
      id: latest-release
      run: echo "release=$(gh release view -R ${{ inputs.repo }} --json tagName --jq .tagName)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: Get tarball from latest release
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: ${{ inputs.repo }}
        version: 'tags/${{ steps.latest-release.outputs.release }}'
        file: '${{ inputs.tarball_prefix }}-${{ steps.latest-release.outputs.release }}.tar.gz'
        token: ${{ inputs.token }}
    - name: Remove placeholder index file
      run: rm ${{ inputs.subdir }}/index.html
      shell: bash
    - name: Extract docs tarball into correct place
      run: tar -xzf ${{ inputs.tarball_prefix }}-${{ steps.latest-release.outputs.release }}.tar.gz -C ${{ inputs.subdir }}
      shell: bash
