name: Deploy prototype unified site

on:
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOCS_DIR: base_site

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: (Lambeq) Get version of latest release
        id: latest-lambeq
        run: echo "release=$(gh release view -R isobelhooper/lambeq --json tagName --jq .tagName)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: (Lambeq) Get tarball from latest release
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: 'isobelhooper/lambeq'
          version: 'tags/${{ steps.latest-lambeq.outputs.release }}'
          file: 'lambeq-docs-${{ steps.latest-lambeq.outputs.release }}.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: (Lambeq) Remove placeholder index file
        run: rm ${{ env.DOCS_DIR }}/lambeq/index.html
      - name: (Lambeq) Extract docs tarball into correct place
        run: tar -xzf lambeq-docs-${{ steps.latest-lambeq.outputs.release }}.tar.gz -C ${{ env.DOCS_DIR }}/lambeq
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
