on:
  push:
    branches:
      - 'gh-pages'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages 
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: base_site
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
